### ISSUE TITLE
训练时没有加question以外的prompt吗？

### ISSUE THREAD

**Issue by xyfZzz** [fairyshine/Seal-Tools#1]
你好，请问训练时没有加question以外的prompt吗？

**Comment by fairyshine** [comment]
Hello! Thank you for your interest in this work.
Yes, we did use the extra prompt.
We have uploaded train data examples just now in the file:
https://github.com/fairyshine/Seal-Tools/blob/master/LLM_Evaluation/data/example.json

Just let me know if you have more questions! Wish you all the best!
