### ISSUE TITLE
Do you plan to release the dataset used in paper for reproducibility

### ISSUE THREAD

**Issue by JasonZhu1313** [fairyshine/Seal-Tools#2]

**Comment by fairyshine** [comment]
Dataset we constructed can be found in https://github.com/fairyshine/Seal-Tools/tree/master/Seal-Tools_Dataset .
Just let me know if you have more questions! Wish you all the best!

**Comment by JasonZhu1313** [comment]
Cool cool thanks, great work

**Comment by JasonZhu1313** [comment]
Hey a qq @fairyshine ,

I saw the train.jsonl is formatted in this way: 

[API call, Query]

Shouldn't each row in training data also contains a set of relevant tools / candidate tools in prompt? For model to select? 

[API lists, Actual API Call, Query]?

Thanks,
Jason

**Comment by fairyshine** [comment]
> Hey a qq @fairyshine ,
> 
> I saw the train.jsonl is formatted in this way:
> 
> [API call, Query]
> 
> Shouldn't each row in training data also contains a set of relevant tools / candidate tools in prompt? For model to select?
> 
> [API lists, Actual API Call, Query]?
> 
> Thanks, Jason

Hey, in our experiment setting, we use the retriever to find the needed tools from the whole tool pool. So there isn't any candidate tool list.

**Comment by JasonZhu1313** [comment]
Thanks for fast response, yes I understand during inference we use retriever to fetch the relevant tools. But the training data should contain a list of tools fetched from the retriever and the ground truth tool if the fetched tools don't include the ground truth? The released data seemed to only contain ground truth

**Comment by fairyshine** [comment]
> Thanks for fast response, yes I understand during inference we use retriever to fetch the relevant tools. But the training data should contain a list of tools fetched from the retriever and the ground truth tool if the fetched tools don't include the ground truth? The released data seemed to only contain ground truth

Considering the context length, we only list gold tools for multi-tool instance in the prompt for training in the format here https://github.com/fairyshine/Seal-Tools/tree/master/LLM_Evaluation/data .
If you want to implement the result , for retriever, we have provided the train dataset for DPR.

Also if you really need the dataset for model training, I can try to upload it (The file's a little big.).

**Comment by fairyshine** [comment]
@JasonZhu1313  
It's new in https://github.com/fairyshine/Seal-Tools/blob/master/Seal-Tools_Dataset/dataset_for_finetune.zip .
Thank you for your concern again!

**Comment by JasonZhu1313** [comment]
Awesome thanks
