### ISSUE TITLE
模型评估

### ISSUE THREAD

**Issue by QingChengLineOne** [fairyshine/Seal-Tools#4]
请问评估代码中的数据集可以提供吗？
![image](https://github.com/user-attachments/assets/81188ed9-ac31-45c3-ae94-2d91aadd836b)

**Comment by fairyshine** [comment]
https://github.com/fairyshine/Seal-Tools/tree/master/Seal-Tools_Dataset
test_in_domain.jsonl和test_out_domain.jsonl即组合成完整的评测集。
