### ISSUE TITLE
ToolLearning_eval函数的问题

### ISSUE THREAD

**Issue by QingChengLineOne** [fairyshine/Seal-Tools#5]
Seal-Tools/Seal-Tools_Dataset文件中的test_in_domain.jsonl的数据格式为[{"api": "getPostmodernTheory", "parameters": {}}, "Retrieve information about postmodern theory."]
而函数中需要的是conversations和id，这对不上呀
![image](https://github.com/user-attachments/assets/c0efc6be-f050-45b6-b0ff-84b5bb2eb889)

**Comment by fairyshine** [comment]
Code in LLM_Evaluation/src/eval.py is only for calculating the score of LLM result.
You should refer to LLM_Evaluation/src/README.md and use LLM_Evaluation/src/inference.py for LLM inference.
Please read the documents and code carefully and thank you for your concentration!
Let me know if you have more questions.

**Comment by QingChengLineOne** [comment]
> Code in LLM_Evaluation/src/eval.py is only for calculating the score of LLM result. You should refer to LLM_Evaluation/src/README.md and use LLM_Evaluation/src/inference.py for LLM inference. Please read the documents and code carefully and thank you for your concentration! Let me know if you have more questions.

![image](https://github.com/user-attachments/assets/f2195062-4baf-4c78-b0b0-7ff063c8ce40)
readme文件说执行Plugin_eval函数进行推理，但是这个函数的数据集和之前提到的数据格式要求是一样的呀
![image](https://github.com/user-attachments/assets/334e385c-7d23-4f21-9010-1ea6a49e47a7)

**Comment by fairyshine** [comment]
> > Code in LLM_Evaluation/src/eval.py is only for calculating the score of LLM result. You should refer to LLM_Evaluation/src/README.md and use LLM_Evaluation/src/inference.py for LLM inference. Please read the documents and code carefully and thank you for your concentration! Let me know if you have more questions.
> 
> ![image](https://private-user-images.githubusercontent.com/111961874/348674097-f2195062-4baf-4c78-b0b0-7ff063c8ce40.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwNDAzNTcsIm5iZiI6MTcyMTA0MDA1NywicGF0aCI6Ii8xMTE5NjE4NzQvMzQ4Njc0MDk3LWYyMTk1MDYyLTRiYWYtNGM3OC1iMGIwLTdmZjA2M2M4Y2U0MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNVQxMDQwNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MDJlNTljYmE4MDYwMjE3Y2VjMGQwMjQ4OWM3M2FlZGUwODI0MzI2OGNmY2Y3Njc3YjMzZGJkZjdmZDIxOWQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.EYJ0b4w6WZzf32r5c4a5uBME_1wqL84ANuRI-Jt-TMM) readme文件说执行Plugin_eval函数进行推理，但是这个函数的数据集和之前提到的数据格式要求是一样的呀 ![image](https://private-user-images.githubusercontent.com/111961874/348675090-334e385c-7d23-4f21-9010-1ea6a49e47a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwNDAzNTcsIm5iZiI6MTcyMTA0MDA1NywicGF0aCI6Ii8xMTE5NjE4NzQvMzQ4Njc1MDkwLTMzNGUzODVjLTdkMjMtNGYyMS05MDEwLTFlYTZhNDllNDdhNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNVQxMDQwNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZGQzMTg3Nzg2M2MwMTljNzVjMjlkMzk5NzhiNjIxZDAwYzc0MWJlZWJjOTNmYTgyNmRmYTgzZDIyOWYyNWE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dPVilIyqEtKDR2FuEiL3VC5IXVAZC7dw1yRFhU5wUos)

We use the shargpt format for finetuning and inference. It's in Seal-Tools_Dataset/dataset_for_finetune.zip.
And actually you can write inference code by yourself for implemention. The code for evaluation is only for reference.
