### ISSUE TITLE
Dataset for Embedding Model

### ISSUE THREAD

**Issue by QuangTQV** [fairyshine/Seal-Tools#6]
Do you have a dataset for fine-tuning the embedding model? The data should be in the form of 'query', 'pos': [list of positive examples], 'neg': [list of hard negative examples].

**Comment by fairyshine** [comment]
You may refer to here: https://github.com/fairyshine/Seal-Tools/tree/master/DPR_Training

**Comment by QuangTQV** [comment]
> You may refer to here: https://github.com/fairyshine/Seal-Tools/tree/master/DPR_Training

do you think finetune cross encoder to rerank tool is ok? i tried but it didn't work

**Comment by fairyshine** [comment]
Yes, just follow the default settings.

**Comment by QuangTQV** [comment]
> Yes, just follow the default settings.
I have tried fine-tuning both the bi-encoder and cross-encoder for the tool retrieval task. The bi-encoder performed quite well, but the cross-encoder could not accomplish the task. I think the cross-encoder is not suitable for tool reranking tasks.

**Comment by QuangTQV** [comment]
> Yes, just follow the default settings.

I have tried fine-tuning both the bi-encoder and cross-encoder for the tool retrieval task. The bi-encoder performed quite well, but the cross-encoder could not accomplish the task. I think the cross-encoder is not suitable for tool reranking tasks.

**Comment by fairyshine** [comment]
I think https://github.com/facebookresearch/DPR use the bi-enocder in default setting?

**Comment by QuangTQV** [comment]
> I think https://github.com/facebookresearch/DPR use the bi-enocder in default setting?

I have fine-tuned a cross encoder, not following the script in that file, but the cross encoder is not effective in the tool selection task. I have only seen people fine-tune bi-encoders for tool retrieval and have not seen anyone fine-tune cross encoders for this task. I don't know the reason why. The cross encoder should be more powerful than the bi-encoder.
